// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vewsuvajuscvwergmfoy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZld3N1dmFqdXNjdndlcmdtZm95Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0NTg2MjMsImV4cCI6MjA3MDAzNDYyM30.WT8anwg2ZY0LUJH0EAVa4lzWwAy6GYY46poFqwI9Cs0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});